Repository JuliaReach/ReachabilityBenchmarks, pull requests merged in 2019-03, with the labels that each got.

#72 Gearbox model
  models/ARCH/AFF/Gearbox/Gearbox.jl
  models/ARCH/AFF/Gearbox/SX_Mesh.cfg
  models/ARCH/AFF/Gearbox/SX_Mesh.xml
  models/ARCH/AFF/Gearbox/SX_Mesh_automatical.cfg
  models/ARCH/AFF/Gearbox/SX_Mesh_manual.xml
  models/ARCH/AFF/Gearbox/SpaceEx/SX_Mesh.cfg
  models/ARCH/AFF/Gearbox/SpaceEx/SX_Mesh.xml
  models/ARCH/AFF/Gearbox/old/Gearbox.ipynb
  models/ARCH/AFF/Gearbox/old/SX_Mesh_automatically.xml
  models/ARCH/AFF/Gearbox/old/SX_mesh.gif
Labels: AFFINE, ARCH19, HYBRID

#76 Use lazy inputs in building
  models/ARCH/AFF/Building/building.jl
  models/ARCH/AFF/Building/building_BFFPSV18.jl
  models/ARCH/AFF/Building/building_benchmark.jl
Labels: AFFINE, ARCH19

#70 WIP - Quadrotor model
  models/ARCH/NLN/Quadrotor/quadrotor.jl
  models/ARCH/NLN/Quadrotor/quadrotor_TMJets.jl
  models/ARCH/NLN/Quadrotor/quadrotor_benchmark.jl
Labels: ARCH19, NONLINEAR

#78 Spacecraft rendezvous
  models/ARCH/AFF/Rendezvous/SpaceEx/SRA01-SR0_.xml
  models/ARCH/AFF/Rendezvous/SpaceEx/SRNA01-SR0_.xml
  models/ARCH/AFF/Rendezvous/SpacecraftRendezvous.jl
  models/ARCH/AFF/Rendezvous/old/4D/COLLISION.cfg
  models/ARCH/AFF/Rendezvous/old/4D/LOS1.cfg
  models/ARCH/AFF/Rendezvous/old/4D/LOS2.cfg
  models/ARCH/AFF/Rendezvous/old/4D/LOS3.cfg
  models/ARCH/AFF/Rendezvous/old/4D/PLOTREACH.cfg
  models/ARCH/AFF/Rendezvous/old/4D/THRUST1.cfg
  models/ARCH/AFF/Rendezvous/old/4D/THRUST2.cfg
  models/ARCH/AFF/Rendezvous/old/4D/VEL1.cfg
  models/ARCH/AFF/Rendezvous/old/4D/VEL2.cfg
  models/ARCH/AFF/Rendezvous/old/4D/VEL3.cfg
  models/ARCH/AFF/Rendezvous/old/4D/VEL4.cfg
  models/ARCH/AFF/Rendezvous/old/4D/VEL5.cfg
  models/ARCH/AFF/Rendezvous/old/4D/VEL6.cfg
  models/ARCH/AFF/Rendezvous/old/4D/VEL7.cfg
  models/ARCH/AFF/Rendezvous/old/4D/VEL8.cfg
  models/ARCH/AFF/Rendezvous/old/4D/genConfigFiles.sh
  models/ARCH/AFF/Rendezvous/old/4D/model_noPass_4d.xml
  models/ARCH/AFF/Rendezvous/old/4D/model_passive_4d.xml
  models/ARCH/AFF/Rendezvous/old/6D/COLLISION.cfg
  models/ARCH/AFF/Rendezvous/old/6D/LOS1.cfg
  models/ARCH/AFF/Rendezvous/old/6D/LOS2.cfg
  models/ARCH/AFF/Rendezvous/old/6D/LOS3.cfg
  models/ARCH/AFF/Rendezvous/old/6D/PLOTREACH.cfg
  models/ARCH/AFF/Rendezvous/old/6D/THRUST1.cfg
  models/ARCH/AFF/Rendezvous/old/6D/THRUST2.cfg
  models/ARCH/AFF/Rendezvous/old/6D/THRUST3.cfg
  models/ARCH/AFF/Rendezvous/old/6D/THRUST4.cfg
  models/ARCH/AFF/Rendezvous/old/6D/VEL1.cfg
  models/ARCH/AFF/Rendezvous/old/6D/VEL2.cfg
  models/ARCH/AFF/Rendezvous/old/6D/VEL3.cfg
  models/ARCH/AFF/Rendezvous/old/6D/VEL4.cfg
  models/ARCH/AFF/Rendezvous/old/6D/VEL5.cfg
  models/ARCH/AFF/Rendezvous/old/6D/VEL6.cfg
  models/ARCH/AFF/Rendezvous/old/6D/VEL7.cfg
  models/ARCH/AFF/Rendezvous/old/6D/VEL8.cfg
  models/ARCH/AFF/Rendezvous/old/6D/genConfigFiles.sh
  models/ARCH/AFF/Rendezvous/old/6D/model_noPass_6d.xml
  models/ARCH/AFF/Rendezvous/old/6D/model_passive_6d.xml
  models/ARCH/AFF/Rendezvous/old/SpacecraftRendezVous.ipynb
Labels: AFFINE, ARCH19, HYBRID

#42 Powertrain model
  models/ARCH/AFF/Powertrain/Powertrain.jl
  models/ARCH/AFF/Powertrain/old/Drivetrain.ipynb
  models/ARCH/AFF/Powertrain/old/Drivetrain_save.ipynb
  models/ARCH/AFF/Powertrain/old/drivetrain_theta1_100percent.cfg
  models/ARCH/AFF/Powertrain/old/drivetrain_theta1_100percent.xml
  models/ARCH/AFF/Powertrain/old/drivetrain_theta1_100percent_flat_automatically.xml
  models/ARCH/AFF/Powertrain/old/drivetrain_theta1_5percent.cfg
  models/ARCH/AFF/Powertrain/old/drivetrain_theta1_5percent.xml
  models/ARCH/AFF/Powertrain/old/drivetrain_theta1_5percent_flat_manually.xml
  models/ARCH/AFF/Powertrain/old/runSXDriveTrain.jl
  models/ARCH/AFF/Powertrain/run_Powertrain.jl
Labels: ARCH19
